# Generated by Django 4.2.10 on 2024-02-26 21:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_baskets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Baskets',
            new_name='Basket',
        ),
    ]
