# Generated by Django 4.2.10 on 2024-02-27 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_baskets_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
